### ISSUE TITLE
📋 Clipboard

### ISSUE THREAD

**Issue by jd-solanki** [jd-solanki/upakarana#3]
## Phase 1

> Docs: `xclip` is required on linux because QClipboard doesn't work when app is not focused

- [ ] Add time in clipboard
- [x] Sort by latest entry
- [ ] If clipboard content has multiple lines only show single line and truncate the rest of the content
- [ ] Hide app window when user clipboard history is used
- [ ] Check on all platforms
	- [x] mac
	- [ ] linux
	- [ ] windows

## Phase 2

- [ ] How to handle binary files
- [ ] Show full text / preview of the binary on the right like raycast
